export const TAROT_DECK = [
  // MAJOR ARCANA
  { name: "The Fool", num: "0", keywords: "Beginnings · Spontaneity · Leap" },
  { name: "The Magician", num: "I", keywords: "Will · Skill · Manifestation" },
  { name: "The High Priestess", num: "II", keywords: "Intuition · Mystery · Stillness" },
  { name: "The Empress", num: "III", keywords: "Abundance · Creation · Nature" },
  { name: "The Emperor", num: "IV", keywords: "Structure · Authority · Foundation" },
  { name: "The Hierophant", num: "V", keywords: "Tradition · Guidance · Institution" },
  { name: "The Lovers", num: "VI", keywords: "Union · Choice · Alignment" },
  { name: "The Chariot", num: "VII", keywords: "Control · Drive · Victory" },
  { name: "Strength", num: "VIII", keywords: "Courage · Patience · Inner Power" },
  { name: "The Hermit", num: "IX", keywords: "Solitude · Wisdom · Inner Light" },
  { name: "Wheel of Fortune", num: "X", keywords: "Cycles · Fate · Turning Points" },
  { name: "Justice", num: "XI", keywords: "Truth · Balance · Law" },
  { name: "The Hanged Man", num: "XII", keywords: "Surrender · Suspension · Perspective" },
  { name: "Death", num: "XIII", keywords: "Transformation · Endings · Release" },
  { name: "Temperance", num: "XIV", keywords: "Alchemy · Flow · Integration" },
  { name: "The Devil", num: "XV", keywords: "Bondage · Shadow · Materialism" },
  { name: "The Tower", num: "XVI", keywords: "Disruption · Revelation · Collapse" },
  { name: "The Star", num: "XVII", keywords: "Hope · Renewal · Guidance" },
  { name: "The Moon", num: "XVIII", keywords: "Illusion · Depth · The Unconscious" },
  { name: "The Sun", num: "XIX", keywords: "Vitality · Clarity · Joy" },
  { name: "Judgement", num: "XX", keywords: "Awakening · Calling · Reckoning" },
  { name: "The World", num: "XXI", keywords: "Completion · Integration · Wholeness" },
  // WANDS
  { name: "Ace of Wands", num: "W1", keywords: "Inspiration · New Passion · Potential" },
  { name: "Two of Wands", num: "W2", keywords: "Planning · Discovery · Future Vision" },
  { name: "Three of Wands", num: "W3", keywords: "Expansion · Foresight · Strategy" },
  { name: "Four of Wands", num: "W4", keywords: "Celebration · Harmony · Foundation" },
  { name: "Five of Wands", num: "W5", keywords: "Conflict · Competition · Tension" },
  { name: "Six of Wands", num: "W6", keywords: "Victory · Recognition · Pride" },
  { name: "Seven of Wands", num: "W7", keywords: "Defense · Perseverance · Boundaries" },
  { name: "Eight of Wands", num: "W8", keywords: "Speed · Action · Quick Momentum" },
  { name: "Nine of Wands", num: "W9", keywords: "Resilience · Grit · Final Push" },
  { name: "Ten of Wands", num: "W10", keywords: "Burden · Overwork · Responsibility" },
  { name: "Page of Wands", num: "WP", keywords: "Exploration · Excitement · Free Spirit" },
  { name: "Knight of Wands", num: "WN", keywords: "Action · Adventure · Impulsiveness" },
  { name: "Queen of Wands", num: "WQ", keywords: "Charisma · Confidence · Independence" },
  { name: "King of Wands", num: "WK", keywords: "Vision · Leadership · Boldness" },
  // CUPS
  { name: "Ace of Cups", num: "C1", keywords: "Emotional Flow · Intuition · New Love" },
  { name: "Two of Cups", num: "C2", keywords: "Partnership · Connection · Mutual Attraction" },
  { name: "Three of Cups", num: "C3", keywords: "Friendship · Community · Joy" },
  { name: "Four of Cups", num: "C4", keywords: "Apathy · Contemplation · Disconnect" },
  { name: "Five of Cups", num: "C5", keywords: "Loss · Grief · Focus on the Past" },
  { name: "Six of Cups", num: "C6", keywords: "Nostalgia · Innocence · Childhood" },
  { name: "Seven of Cups", num: "C7", keywords: "Illusion · Choices · Imagination" },
  { name: "Eight of Cups", num: "C8", keywords: "Walking Away · Seeking Truth · Transition" },
  { name: "Nine of Cups", num: "C9", keywords: "Satisfaction · Wishes Fulfilled · Comfort" },
  { name: "Ten of Cups", num: "C10", keywords: "Alignment · Emotional Completion · Peace" },
  { name: "Page of Cups", num: "CP", keywords: "Curiosity · Synchronicity · Creative Spark" },
  { name: "Knight of Cups", num: "CN", keywords: "Romance · Charm · Idealism" },
  { name: "Queen of Cups", num: "CQ", keywords: "Compassion · Empathy · Emotional Security" },
  { name: "King of Cups", num: "CK", keywords: "Emotional Balance · Diplomacy · Wisdom" },
  // SWORDS
  { name: "Ace of Swords", num: "S1", keywords: "Breakthrough · Clarity · Sharp Intellect" },
  { name: "Two of Swords", num: "S2", keywords: "Indecision · Stalemate · Blocked Vision" },
  { name: "Three of Swords", num: "S3", keywords: "Heartbreak · Sorrow · Painful Truth" },
  { name: "Four of Swords", num: "S4", keywords: "Rest · Restoration · Mental Break" },
  { name: "Five of Swords", num: "S5", keywords: "Conflict · Win at All Costs · Hostility" },
  { name: "Six of Swords", num: "S6", keywords: "Transition · Moving On · Calmer Waters" },
  { name: "Seven of Swords", num: "S7", keywords: "Strategy · Deception · Tactical Retreat" },
  { name: "Eight of Swords", num: "S8", keywords: "Restriction · Victim Mentality · Trap" },
  { name: "Nine of Swords", num: "S9", keywords: "Anxiety · Nightmares · Overthinking" },
  { name: "Ten of Swords", num: "S10", keywords: "Rock Bottom · Ruin · Inevitable End" },
  { name: "Page of Swords", num: "SP", keywords: "Curiosity · Restless Mind · Vigilance" },
  { name: "Knight of Swords", num: "SN", keywords: "Ambition · Haste · Driven Intellect" },
  { name: "Queen of Swords", num: "SQ", keywords: "Clear Boundaries · Logic · Independence" },
  { name: "King of Swords", num: "SK", keywords: "Mental Clarity · Truth · Intellectual Power" },
  // PENTACLES
  { name: "Ace of Pentacles", num: "P1", keywords: "New Opportunity · Manifestation · Resource" },
  { name: "Two of Pentacles", num: "P2", keywords: "Balance · Adaptability · Juggling Priorities" },
  { name: "Three of Pentacles", num: "P3", keywords: "Collaboration · Craftsmanship · Teamwork" },
  { name: "Four of Pentacles", num: "P4", keywords: "Conservation · Scarcity Mindset · Control" },
  { name: "Five of Pentacles", num: "P5", keywords: "Hardship · Isolation · Material Loss" },
  { name: "Six of Pentacles", num: "P6", keywords: "Generosity · Charity · Reciprocity" },
  { name: "Seven of Pentacles", num: "P7", keywords: "Patience · Investment · Long-term View" },
  { name: "Eight of Pentacles", num: "P8", keywords: "Mastery · Focus · Dedicated Work" },
  { name: "Nine of Pentacles", num: "P9", keywords: "Luxury · Self-Sufficiency · Independence" },
  { name: "Ten of Pentacles", num: "P10", keywords: "Legacy · Wealth · Long-term Stability" },
  { name: "Page of Pentacles", num: "PP", keywords: "Diligence · Study · Grounded Ambition" },
  { name: "Knight of Pentacles", num: "PN", keywords: "Routine · Reliability · Hard Work" },
  { name: "Queen of Pentacles", num: "PQ", keywords: "Nurturing · Practicality · Security" },
  { name: "King of Pentacles", num: "PK", keywords: "Enterprise · Abundance · Stable Power" }
];
